name: KBuild

on:
  workflow_dispatch:

jobs:
  kb:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt-get update -y &>/dev/null || sudo apt-get update -y &>/dev/null || true
        sudo apt-get upgrade -y &>/dev/null || sudo apt-get upgrade -y &>/dev/null || true
        sudo apt-get install brotli zip zstd tar lz4 cpio xz-utils pahole libelf-dev python2 -y || sudo apt-get install python2 pahole libelf-dev brotli zip zstd tar lz4 cpio xz-utils -y
    - name: Build
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        bash build.sh
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Kernels_a14
        path: kernel_build/ExynosUnbound*
